{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maersk-exporter.fullname" . }}
  labels:
    {{- include "maersk-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  maersk-consumer-key: {{ .Values.credentials.maerskConsumerKey | quote }}
  aisstream-api-key: {{ .Values.credentials.aisstreamApiKey | quote }}
{{- end }}
